### ISSUE TITLE
cpjku_dcase23

### ISSUE THREAD

**Issue by Stirve587** [fschmid56/cpjku_dcase23#1]
![cpjku_dcase23](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/db18f3e4-a7ab-4e0c-bea7-90c3eefdaa0a)
Could you tell me how to solve this problem?

**Comment by fschmid56** [comment]
It seems that you don't have the file _fold1_train.csv_ in the correct location. Make sure you correctly download and unzip all the files from this URL: https://zenodo.org/record/6337421

The missing file _fold1_train.csv_ is specifically located in this archive: https://zenodo.org/record/6337421/files/TAU-urban-acoustic-scenes-2022-mobile-development.meta.zip?download=1

**Comment by Stirve587** [comment]
I'm sorry to bother you again. I'm a newbie and I hope you can bear with me. How can I solve this mistake
![1MK~B32WDZI2EQMNQJ8XK0K](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/fd659ff0-488f-4c30-89cd-d367142074de)

**Comment by fschmid56** [comment]
Hi, no problem, and thanks for your interest. 

In general, resampling the waveform is time-consuming and we only want to do it once - therefore we cache the resampled waveforms. The command line argument _cache_path_ specifies in which directory the resampled waveform ends up. Per default _cache_path_ was set to _datasets/cpath_ which caused problems on your OS. I changed it to _os.path.join("datasets", "cpath")_ . I hope this fixes your problem.

**Comment by Stirve587** [comment]
After I  run the run_training.py file,I still get these errors,
![5D09A3C{2$)PBLCCWB({682](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/618bff59-11e5-4a34-9e2a-39e92754dee4)
![BZ}_Q0~TRG5O}J$UXC2 KYL](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/08b582cd-8f79-4906-a892-c334f756e442)
![Z3$)JC$F}H(~PHX 8U(617A](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/50f9a0f2-ab08-4e79-a350-5d3157ba5240)
![YU9N$@T 1EG1 F_8M XK%AC](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/c18144da-474d-4b38-85c5-04b3062931b8)
I hope you can look at it for me when you have time. Thank you very much

**Comment by fschmid56** [comment]
Have you already resolved it? For sure it has something to do with building the paths on your systems (the "\\" and "/" are not matching).

**Comment by Stirve587** [comment]
I have solved the previous problem, and there are still some mistakes after the correction
![QQ图片20231019152213](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/8f67fc4c-5b95-46f7-a9ed-d51b09c589c4)
![QQ图片20231019152251](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/4922a8b8-c7e1-447b-a188-9d0d8efa52b6)

**Comment by fschmid56** [comment]
It seems like the expression _len(self.dirs)_ is 0. Can you verify that and check why this is the case?

**Comment by Stirve587** [comment]
For your original code, I have changed this part according to your readme, and have also modified these two parts, but I have not modified other codes of yours. May I ask why I have encountered this problem and how can I modify it? 
![QQ图片20231022142809](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/645dce61-a837-43c3-96ae-2e21f7094cfc)
Thank you very much for your reply
![QQ图片20231022142841](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/b374a63b-adfb-4803-8c10-cc54c1210349)

**Comment by Stirve587** [comment]
I am very sorry that data set 4 was not put in due to my negligence, which caused some errors,but now there is a new problem, I have checked some information but still have not solved, I hope you can give me some advice, thank you very 
![QQ图片20231025142229](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/76e64ee6-494a-403a-a9c7-e1af4668e4a6)
much

**Comment by Stirve587** [comment]
My dear author, do you have time to reply me? I feel that I am about to get rid of this problem. I hope you can reply as soon as possible

**Comment by Stirve587** [comment]
Thanks for your help these days, I have been running successfully

**Comment by fschmid56** [comment]
Hi! I'm glad to hear that the code works for you now. I apologize for the lack of responsiveness, I have been very busy lately.

**Comment by Stirve587** [comment]
You are the best author I have ever seen. I hope you can achieve greater achievements in your field. Thank you for your guidance

**Comment by Stirve587** [comment]
![ZY4HYZ8 WROB%WQ_O~_X)03](https://github.com/fschmid56/cpjku_dcase23/assets/144822516/f7ccfe2d-8ab4-4ebb-b16a-5de940aac128)
I have such a problem after running, how can I solve it

**Comment by fschmid56** [comment]
I haven't encountered this specific error so far. Is the training correctly logged to wandb? Or is any information lost?

**Comment by Augenstern1120** [comment]
Have you ever encountered this kind of problem：RuntimeError: stack expects each tensor to be equal size, but got [1, 32000] at entry 0 and [1, 320000] at entry 46

**Comment by fschmid56** [comment]
I'm afraid, I have not encountered this problem before. Can you provide more information on where the problem occurs? It seems that you are dealing with a 1-second and a 10-second audio file.
