### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by 11545s** [fschmid56/cpjku_dcase23#2]
作者您好，读了您的文章我感觉非常好，想在您的代码基础上进行研究，想问一下，比如我给教师模型里加一个即插即用的注意力模块，我该怎么训练使得效果提高呢

**Comment by Stirve587** [comment]
你好，我也在研究这篇论文和代码，请问可以加您一下联系方式吗，想向您学习一下

**Comment by 11545s** [comment]
我微信18347094275




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fschmid56/cpjku_dcase23"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月25日(星期三) 下午2:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fschmid56/cpjku_dcase23] 问题咨询 (Issue #2)





 
你好，我也在研究这篇论文和代码，请问可以加您一下联系方式吗，想向您学习一下

**Comment by Augenstern1120** [comment]
Have you ever encountered this kind of problem：RuntimeError: stack expects each tensor to be equal size, but got [1, 32000] at entry 0 and [1, 320000] at entry 46
