### ISSUE TITLE
pre-trained teacher model

### ISSUE THREAD

**Issue by dreamcatcher-zgr** [fschmid56/cpjku_dcase23#3]
could you tell me how can I obtain the pre-trained teacher models?

**Comment by Stirve587** [comment]
Where are you from? Can I add your contact information

**Comment by Stirve587** [comment]
Did your code get out?

**Comment by dreamcatcher-zgr** [comment]
I'm from China, you can contact me via the email zgrzgrr@gmail.com

**Comment by fschmid56** [comment]
The pre-trained teacher models can be found in the release: 

https://github.com/fschmid56/cpjku_dcase23/releases/tag/ensemble_logits
