### ISSUE TITLE
Using the evaluation dataset

### ISSUE THREAD

**Issue by imnu13674850462** [fschmid56/cpjku_dcase23#4]
Hello, author. I would like to inquire about how to evaluate using the TAU Urban Acoustic Scenes 2023 Mobile Evaluation dataset. In which file can I find the evaluation process, and how is this evaluation set used and configured?

**Comment by Augenstern1120** [comment]
May I ask what is the reason for this error. Thank you very much for your achievements. I am a college student who is new to ASC.
1703419926032

Epoch 0: 2%|██▏ | 15/662 [00:13<09:41, 1.11it/s, loss=0.509, v_num=5k97]Traceback (most recent call last):
RuntimeError: stack expects each tensor to be equal size, but got [1, 32000] at entry 0 and [1, 320000] at entry 46

Epoch 0: 1%|▉ | 6/662 [00:03<07:03, 1.55it/s, loss=0.511, v_num=lxs6]
RuntimeError: Caught RuntimeError in DataLoader worker process 6.
RuntimeError: stack expects each tensor to be equal size, but got [1, 32000] at entry 0 and [1, 320000] at entry 249

**Comment by fschmid56** [comment]
Hi, the TAU Urban Acoustic Scenes 2022 Mobile dataset comes with a split into train, test, and evaluation sets. However, for the evaluation set the labels are not publicly available. They are kept by the challenge organizers to evaluate submitted systems. 

Are you asking for the code that can generate the predictions for the evaluation set files ready to be submitted to the challenge? Other than that, this repo only implements validation on the publicly available test set.
