### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [1, 32000] at entry 0 and [1, 320000] at entry 255

### ISSUE THREAD

**Issue by Augenstern1120** [fschmid56/cpjku_dcase23#6]
May I ask what is the reason for this error. Thank you very much for your achievements. I am a college student who is new to ASC.
![1703419926032](https://github.com/fschmid56/cpjku_dcase23/assets/143238177/4597f451-6858-4a48-aac8-279b1cb76447)

Epoch 0:   2%|██▏                                                                                                | 15/662 [00:13<09:41,  1.11it/s, loss=0.509, v_num=5k97]Traceback (most recent call last):
RuntimeError: stack expects each tensor to be equal size, but got [1, 32000] at entry 0 and [1, 320000] at entry 46

Epoch 0:   1%|▉                                                                                                   | 6/662 [00:03<07:03,  1.55it/s, loss=0.511, v_num=lxs6]
RuntimeError: Caught RuntimeError in DataLoader worker process 6.
RuntimeError: stack expects each tensor to be equal size, but got [1, 32000] at entry 0 and [1, 320000] at entry 249

**Comment by Augenstern1120** [comment]
Hello everyone, I have solved this problem, but I am not sure about the specifics. I solved the problem by deleting the files in Wandb. Once again, thank the author for their work!

**Comment by ccliangxd** [comment]
> 请问这个错误的原因是什么？非常感谢你们所取得的成就。我是一名刚接触 ASC 的大学生。 ![1703419926032](https://private-user-images.githubusercontent.com/143238177/292669713-4597f451-6858-4a48-aac8-279b1cb76447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjA4NTAsIm5iZiI6MTcwNTA2MDU1MCwicGF0aCI6Ii8xNDMyMzgxNzcvMjkyNjY5NzEzLTQ1OTdmNDUxLTY4NTgtNGE0OC1hYWM4LTI3OWIxY2I3NjQ0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxMTU1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODMyMDdkODZlOTlhMDBjMjBlZjllNGU5ZjJiZWQ0NzBkNTk2NDJjNTFkNjVkN2QwYWY4ZTBjODkwODVkMmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KiqdWf5wSmBZeQ7elFLl1xHM38AgYraPCZ_U5F-x6B0)
> 
> 纪元 0：2%|██▏ | 15/662 [00:13<09:41，1.11it/s，loss=0.509，v_num=5k97]回溯（最近一次调用最后）： 运行时错误：堆栈期望每个张量大小相等，但得到 [1, 32000 ] 在条目 0 和 [1, 320000] 在条目 46
> 
> 纪元 0：1%|▉ | 6/662 [00:03<07:03, 1.55it/s, loss=0.511, v_num=lxs6] RuntimeError: 在 DataLoader 工作进程 6 中捕获 RuntimeError。 RuntimeError: 堆栈期望每个张量大小相等，但得到 [1 , 32000] 在条目 0 处，[1, 320000] 在条目 249 处

It seems that your data length is different. It is recommended to check the data length. If it is different, you can use zero padding to ensure that the data remains the same length

**Comment by ccliangxd** [comment]
> 请问这个错误的原因是什么？非常感谢你们所取得的成就。我是一名刚接触 ASC 的大学生。 ![1703419926032](https://private-user-images.githubusercontent.com/143238177/292669713-4597f451-6858-4a48-aac8-279b1cb76447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjE0NzIsIm5iZiI6MTcwNTA2MTE3MiwicGF0aCI6Ii8xNDMyMzgxNzcvMjkyNjY5NzEzLTQ1OTdmNDUxLTY4NTgtNGE0OC1hYWM4LTI3OWIxY2I3NjQ0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxMjA2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWM3MGEyNTA0MDlhODJiYjU0MTAzZDZkOGZiMDQ5M2JiNWJhMzI1YjZjYTVlMTUzZDliYWNiOWM3MWEyNjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rbYF_4QK3h7ROP6hLeJz65AWl1y83iN7d4cYrtv6yho)
> 
> 纪元 0：2%|██▏ | 15/662 [00:13<09:41，1.11it/s，loss=0.509，v_num=5k97]回溯（最近一次调用最后）： 运行时错误：堆栈期望每个张量大小相等，但得到 [1, 32000 ] 在条目 0 和 [1, 320000] 在条目 46
> 
> 纪元 0：1%|▉ | 6/662 [00:03<07:03, 1.55it/s, loss=0.511, v_num=lxs6] RuntimeError: 在 DataLoader 工作进程 6 中捕获 RuntimeError。 RuntimeError: 堆栈期望每个张量大小相等，但得到 [1 , 32000] 在条目 0 处，[1, 320000] 在条目 249 处

It is recommended that you check the error through debug and modify it

**Comment by Augenstern1120** [comment]
> > 请问这个错误的原因是什么？非常感谢你们所取得的成就。我是一名刚接触 ASC 的大学生。 ![1703419926032](https://private-user-images.githubusercontent.com/143238177/292669713-4597f451-6858-4a48-aac8-279b1cb76447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjE0NzIsIm5iZiI6MTcwNTA2MTE3MiwicGF0aCI6Ii8xNDMyMzgxNzcvMjkyNjY5NzEzLTQ1OTdmNDUxLTY4NTgtNGE0OC1hYWM4LTI3OWIxY2I3NjQ0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxMjA2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWM3MGEyNTA0MDlhODJiYjU0MTAzZDZkOGZiMDQ5M2JiNWJhMzI1YjZjYTVlMTUzZDliYWNiOWM3MWEyNjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rbYF_4QK3h7ROP6hLeJz65AWl1y83iN7d4cYrtv6yho)
> > 纪元 0：2%|██▏ | 15/662 [00:13<09:41，1.11it/s，loss=0.509，v_num=5k97]回溯（最近一次调用最后）： 运行时错误：堆栈期望每个张量大小相等，但得到 [1, 32000 ] 在条目 0 和 [1, 320000] 在条目 46
> > 纪元 0：1%|▉ | 6/662 [00:03<07:03, 1.55it/s, loss=0.511, v_num=lxs6] RuntimeError: 在 DataLoader 工作进程 6 中捕获 RuntimeError。 RuntimeError: 堆栈期望每个张量大小相等，但得到 [1 , 32000] 在条目 0 处，[1, 320000] 在条目 249 处
> 
> It is recommended that you check the error through debug and modify it
Thank you very much！May I ask which file is the code for the teacher model to guide the student model in? Where does the code reflect knowledge distillation?
（非常感谢！我已经解决啦！把存储的mel图缓存删除就可以解决。
请问教师模型指导学生模型的代码在哪个文件中？哪里体现知识蒸馏的代码？）

**Comment by fschmid56** [comment]
Knowledge Distillation can be found in the file 'run_training.py', specifically in the lines 110-115.

Note that the teacher predictions are computed offline (before the training of the student model). The teacher logits are automatically downloaded when running the 'run_training.py' file.

**Comment by Augenstern1120** [comment]
> Knowledge Distillation can be found in the file 'run_training.py', specifically in the lines 110-115.
> 
> Note that the teacher predictions are computed offline (before the training of the student model). The teacher logits are automatically downloaded when running the 'run_training.py' file.

Thank you very much for your reply! I am a freshman, and I have another question. How did ensemble _logits, that is, teacher logits, obtained through multiple models? I don't seem to see the code about ensemble _logits.

**Comment by fschmid56** [comment]
What we have in this repo:
- Code for training teacher models: 'run_cp-resnet_training.py' and 'run_passt_training.py'
- Pre-trained teacher models: https://github.com/fschmid56/cpjku_dcase23/releases/tag/ensemble_logits
- Example of how to use pre-trained teacher models for inference: 'run_teacher_validation.py'

If you want to build your own teacher ensemble you would need to:
1. Run inference on the whole training set with the trained teacher model
2. Save the logits computed for each training set file to disk
3. Repeat 1. and 2. for all models that should be included in the ensemble
4. Average the logits of all models you would like to use to build the teacher ensemble

This is also how the ensemble_logits in this repo have been created.

**Comment by Augenstern1120** [comment]
> What we have in this repo:
> 
> * Code for training teacher models: 'run_cp-resnet_training.py' and 'run_passt_training.py'
> * Pre-trained teacher models: https://github.com/fschmid56/cpjku_dcase23/releases/tag/ensemble_logits
> * Example of how to use pre-trained teacher models for inference: 'run_teacher_validation.py'
> 
> If you want to build your own teacher ensemble you would need to:
> 
> 1. Run inference on the whole training set with the trained teacher model
> 2. Save the logits computed for each training set file to disk
> 3. Repeat 1. and 2. for all models that should be included in the ensemble
> 4. Average the logits of all models you would like to use to build the teacher ensemble
> 
> This is also how the ensemble_logits in this repo have been created.

Thank you for your response. I've noticed that there are 460,700 rows in the "ensemble_logits" data, but only 139,620 audio samples in the training set.

How is the one-to-one correspondence maintained during training? Where in the code is this implemented to ensure each audio sample corresponds to its respective logits?
Does shuffling the data during loading have any impact?

**Comment by Augenstern1120** [comment]
> What we have in this repo:
> 
> * Code for training teacher models: 'run_cp-resnet_training.py' and 'run_passt_training.py'
> * Pre-trained teacher models: https://github.com/fschmid56/cpjku_dcase23/releases/tag/ensemble_logits
> * Example of how to use pre-trained teacher models for inference: 'run_teacher_validation.py'
> 
> If you want to build your own teacher ensemble you would need to:
> 
> 1. Run inference on the whole training set with the trained teacher model
> 2. Save the logits computed for each training set file to disk
> 3. Repeat 1. and 2. for all models that should be included in the ensemble
> 4. Average the logits of all models you would like to use to build the teacher ensemble
> 
> This is also how the ensemble_logits in this repo have been created.

Thank you very much for your response! I've noticed that there are 460,700 rows of data in the "ensemble_logits," whereas there are only 139,620 audio samples in the training set and 29,680 audio samples in the test set.

I have another question about KD and I hope to receive your reply! Thank you very much!

1.During training, how does the correspondence between each row in 'ensemble_logits' and an individual audio file occur? It seems that I have not come across a section in the code that implements this one-to-one correspondence.

2.Will the shuffle operation when loading data impact this one-to-one alignment?

3.Considering that the training set consists of only 139,620 audio samples and the test set has 29,680, what constitutes the remaining audio entries out of the 460,700 total? Are there other audio segments apart from the ones in the training and test sets?

**Comment by fschmid56** [comment]
If you check out the table on the [official website](https://dcase.community/challenge2023/task-low-complexity-acoustic-scene-classification), there are 230,350 data points in total (train + test + some unused datapoints). 

When creating the teacher labels, we labeled all 230,350 data points for simplicity and then just index only the ones we want to use in the AddLogitsDataset in the [dataset file](https://github.com/fschmid56/cpjku_dcase23/blob/main/datasets/dcase23.py#L160).

The complete logits file contains 460,700 (= 2 * 230,350) rows, because we use "Shifted Crops" augmentation, which you can lookup in [this report](https://dcase.community/documents/challenge2023/technical_reports/DCASE2023_Schmid_28_t1.pdf).

1. AddLogitsDataset in the [dataset file](https://github.com/fschmid56/cpjku_dcase23/blob/main/datasets/dcase23.py#L160)
2. It will not impact this alignment, since shuffling is an aspect of the Dataloader, while loading the correct teacher logits is an aspect of the Dataset
3. See answer above

**Comment by Augenstern1120** [comment]
> If you check out the table on the [official website](https://dcase.community/challenge2023/task-low-complexity-acoustic-scene-classification), there are 230,350 data points in total (train + test + some unused datapoints).
> 
> When creating the teacher labels, we labeled all 230,350 data points for simplicity and then just index only the ones we want to use in the AddLogitsDataset in the [dataset file](https://github.com/fschmid56/cpjku_dcase23/blob/main/datasets/dcase23.py#L160).
> 
> The complete logits file contains 460,700 (= 2 * 230,350) rows, because we use "Shifted Crops" augmentation, which you can lookup in [this report](https://dcase.community/documents/challenge2023/technical_reports/DCASE2023_Schmid_28_t1.pdf).
> 
> 1. AddLogitsDataset in the [dataset file](https://github.com/fschmid56/cpjku_dcase23/blob/main/datasets/dcase23.py#L160)
> 2. It will not impact this alignment, since shuffling is an aspect of the Dataloader, while loading the correct teacher logits is an aspect of the Dataset
> 3. See answer above
Thank you very much for your reply. I noticed that the model-int8 parameter count is 12k while executing run_qat.py
![image](https://github.com/fschmid56/cpjku_dcase23/assets/143238177/0ecc086b-f082-490e-b876-a9c81bb6165d)
However, in line 306 of the run_qat.py file, I calculated the number of parameters immediately after **prepare_quantified (pl_module)**, which is still 124K. The values for macs and params in line 311 are printed as 0,124862. 
My question is: 1. May I ask at which step was 12K measured? I haven't found any relevant code.
2. After **prepare_quantified**, the quantification is completed. Why hasn't the parameter quantity changed
I am very much looking forward to receiving your reply. Thank you very much!

**Comment by Augenstern1120** [comment]
> If you check out the table on the [official website](https://dcase.community/challenge2023/task-low-complexity-acoustic-scene-classification), there are 230,350 data points in total (train + test + some unused datapoints).
> 
> When creating the teacher labels, we labeled all 230,350 data points for simplicity and then just index only the ones we want to use in the AddLogitsDataset in the [dataset file](https://github.com/fschmid56/cpjku_dcase23/blob/main/datasets/dcase23.py#L160).
> 
> The complete logits file contains 460,700 (= 2 * 230,350) rows, because we use "Shifted Crops" augmentation, which you can lookup in [this report](https://dcase.community/documents/challenge2023/technical_reports/DCASE2023_Schmid_28_t1.pdf).
> 
> 1. AddLogitsDataset in the [dataset file](https://github.com/fschmid56/cpjku_dcase23/blob/main/datasets/dcase23.py#L160)
> 2. It will not impact this alignment, since shuffling is an aspect of the Dataloader, while loading the correct teacher logits is an aspect of the Dataset
> 3. See answer above



I am honored to receive your response! I have observed that when inspecting the dictionary in the ckpt file generated by run_qat.py using the function **torch.load(filename.ckpt)['state_dict']**, the values are all float32, not int8. What could be causing this phenomenon?
Considering the accuracy drop witnessed in run_qat.py, I infer that the quantization-aware training (QAT) is indeed having an effect; hence, I am puzzled by this inconsistency.
Looking forward to your reply! 

![image](https://github.com/fschmid56/cpjku_dcase23/assets/143238177/1f436eb5-5ef9-4312-9c88-50b3464b3807)

**Comment by fschmid56** [comment]
Note that the pytorch module has two different models:
- 'model': the model which allows QAT, but is not quantized itself
- 'model_int8': the quantized model

There is a callback used in our pytorch lightening module that makes sure that 'model_int8' is updated on the start of each validation epoch. This is how the quantization step looks like:

`pl_module.model_int8 = torch.ao.quantization.convert(pl_module.model, inplace=False)`

You need to check the parameters of 'model_int8', these should be of int8 data type. Looking at the model outputs also wouldn't work, because these are automatically dequantized by the model.

**Comment by Augenstern1120** [comment]
> Note that the pytorch module has two different models:
> 
> * 'model': the model which allows QAT, but is not quantized itself
> * 'model_int8': the quantized model
> 
> There is a callback used in our pytorch lightening module that makes sure that 'model_int8' is updated on the start of each validation epoch. This is how the quantization step looks like:
> 
> `pl_module.model_int8 = torch.ao.quantization.convert(pl_module.model, inplace=False)`
> 
> You need to check the parameters of 'model_int8', these should be of int8 data type. Looking at the model outputs also wouldn't work, because these are automatically dequantized by the model.


Thank you very much for your response! I noticed that **run_qat.py** only saves one ckpt file, which means the only saved model file is 'model': the model which allows QAT, but is not quantized itself.' However, it did not save the int8 ckpt model file. Can I understand it this way?

I have a little more question

1.How can I save the int8 model file?

2.The interface displayed by running the qat main program is as shown in the following picture, and I am confused what Params refers to here? Because quantization should not change the number of parameters in the model. Shouldn't the number of parameters for model and model-int8 be the same?
![image](https://github.com/fschmid56/cpjku_dcase23/assets/143238177/f81eb6cd-07f3-4e17-8ca7-d9bad8980954)

Looking forward to your reply. Thank you once again for your invaluable assistance.

**Comment by fschmid56** [comment]
> 1. How can I save the int8 model file?

If the 'model_int8' is not stored in the checkpoint (which might be the case, I don't remember), you can simply obtain it by loading the weights of 'model' and using the following line:

`model_int8 = torch.ao.quantization.convert(model, inplace=False)`

> 2. The interface displayed by running the qat main program is as shown in the following picture, and I am confused what Params refers to here? Because quantization should not change the number of parameters in the model. Shouldn't the number of parameters for model and model-int8 be the same?

Yes, the number of parameters is the same. After quantization, most tools to count the number of parameters/MACs are not working correctly. You should count the number of parameters before doing the conversion to _int8_
